// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ZgMt5Cd0pluf4oG9ihsrbuFmEhLVHw0',
    appId: '1:773658683983:android:4934897ab380108a34d83a',
    messagingSenderId: '773658683983',
    projectId: 'flutter-chat-app-371cc',
    storageBucket: 'flutter-chat-app-371cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEF8rc8nLIe6VVvK8HXjPOhAVd6Ep_IDs',
    appId: '1:773658683983:ios:9ffc5d0ea1dd777a34d83a',
    messagingSenderId: '773658683983',
    projectId: 'flutter-chat-app-371cc',
    storageBucket: 'flutter-chat-app-371cc.firebasestorage.app',
    iosBundleId: 'com.example.section14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjXR9c_t0K-wB-i3Bcsi6IxmeVNBxG7GE',
    appId: '1:773658683983:web:359979eaa65105ed34d83a',
    messagingSenderId: '773658683983',
    projectId: 'flutter-chat-app-371cc',
    authDomain: 'flutter-chat-app-371cc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-371cc.firebasestorage.app',
  );

}